### ISSUE TITLE
MPLAB Harmony3/PLIB connection

### ISSUE THREAD

**Issue by timscheuermann** [CANopenNode/CANopenPIC#11]
Hi,

I try to implement CANopenNode to my MPLAB project (PIC32MK1024MCM100). I generated the HAL (plib-drivers) with MPLAB Harmony3.
Is it possible to create an example project to integrate CANopenNode with those plib drivers? At the moment I am stuck at the point to make your PIC32MX example work with my PIC32MK.
I have to say that I am bound to these Harmony-Generated function.
But more generally it would be "nice to have" if we can use a HAL from Harmony like the CANopenSTM32 examples are doing it with the CubeMX Code generator.

Thank you,
Tim

**Comment by CANopenNode** [comment]
I agree, we can use HAL from Harmony, as you suggest. I can offer some help, but I'm currently not up to date with Microchip tools. Pull requests will be welcome, I may also make some tests.
Please note, CAN-FD is currently not yet supported, configure as classical CAN.
You can also reference CANopenNode/example besides PIC32.

**Comment by xzwxiaobu** [comment]
> Hi,
> 
> I try to implement CANopenNode to my MPLAB project (PIC32MK1024MCM100). I generated the HAL (plib-drivers) with MPLAB Harmony3. Is it possible to create an example project to integrate CANopenNode with those plib drivers? At the moment I am stuck at the point to make your PIC32MX example work with my PIC32MK. I have to say that I am bound to these Harmony-Generated function. But more generally it would be "nice to have" if we can use a HAL from Harmony like the CANopenSTM32 examples are doing it with the CubeMX Code generator.
> 
> Thank you, Tim

**Comment by xzwxiaobu** [comment]
I have the same confusion as you. How did you solve this problem? Canopennode is integrated in the mk chip. If it is a lib generated by HARMONY v3, can you provide a demo that is compatible with canopennode for my reference? Thank you.

**Comment by timscheuermann** [comment]
I didnt solve the problem but switched to another CANopen Library where we built the driver together with the developer of the stack and used the Harmony drivers. But with my knowledge of today i would use the given driver in CANopenPIC and port it to the MK-chip and do not use harmony because it is just too buggy. Maybe you can use Harmony to generate a working project for the MCU, but for the CAN-Part I would recommend to go the "Register"-way.

**Comment by xzwxiaobu** [comment]
> I didnt solve the problem but switched to another CANopen Library where we built the driver together with the developer of the stack and used the Harmony drivers. But with my knowledge of today i would use the given driver in CANopenPIC and port it to the MK-chip and do not use harmony because it is just too buggy. Maybe you can use Harmony to generate a working project for the MCU, but for the CAN-Part I would recommend to go the "Register"-way.

yes  ,i will  do  the same way .  can  part  use  canopenPIC  ,others  lib driver  use    Harmony drivers.  by the  way  ,did you use  sdo segmented transfer canopen, i  do not  know  how to use  this  function to  Download Firmware Library. i use the  example  of  demo [github.com/CANopenNode/CANopenPIC/](https://github.com/CANopenNode/CANopenDemo/tree/master/demo/PIC32.X)

**Comment by timscheuermann** [comment]
I have to say I never used CANopenNode. But generally for firmware downloads you can use segmented transfer, which is slow. If you want a faster way you can use sdo block transfer.

**Comment by xzwxiaobu** [comment]
&nbsp;But generally for firmware downloads you can use segmented transfer, which is slow. If you want a faster way you can use sdo block transfer.&nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; I know what&nbsp; you&nbsp; mean ，&nbsp; but&nbsp; i&nbsp; do not&nbsp; konw&nbsp; how&nbsp; to use&nbsp; it&nbsp; bro . if&nbsp; you have&nbsp; time&nbsp; &nbsp;,can&nbsp; you give me&nbsp; &nbsp;a&nbsp; exple or demo&nbsp; to&nbsp; use canopen&nbsp; to&nbsp;&nbsp;downloads&nbsp; mk-chip&nbsp; &nbsp;.
&nbsp; &nbsp; &nbsp;thanks
&nbsp; &nbsp; &nbsp;best wishes&nbsp;




♂&nbsp;Bad&nbsp;Boy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CANopenNode/CANopenPIC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月20日(星期四) 下午3:01
***@***.***&gt;;
抄送:&nbsp;"♂ Bad ***@***.******@***.***&gt;;
主题:&nbsp;Re: [CANopenNode/CANopenPIC] MPLAB Harmony3/PLIB connection (Issue #11)



   
I have to say I never used CANopenNode. But generally for firmware downloads you can use segmented transfer, which is slow. If you want a faster way you can use sdo block transfer.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  timscheuermann left a comment (CANopenNode/CANopenPIC#11)
 
I have to say I never used CANopenNode. But generally for firmware downloads you can use segmented transfer, which is slow. If you want a faster way you can use sdo block transfer.

**Comment by xzwxiaobu** [comment]
> I have to say I never used CANopenNode. But generally for firmware downloads you can use segmented transfer, which is slow. If you want a faster way you can use sdo block transfer.

I know what  you  mean ，  but  i  do not  konw  how  to use  it  bro . if  you have  time   ,can  you give me   a  exple or demo  to  use canopen  to  downloads  mk-chip   .
     thanks
     best wishes

**Comment by CANopenNode** [comment]
Use https://github.com/CANopenNode/CANopenPIC/tree/master/PIC32 as a template. Configure as CAN, not CAN FD. Read the PIC32MK1024MCM100 datasheet. Learn C and CANopen (book).
